language: cpp
script: cmake
compiler: 
  - clang
os:
  - linux
script:
  - cd build
  - cmake .. && make
sudo: required
dist: trusty
addons:
  apt:
    sources:  
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
    packages:
      - clang-3.7
      - g++-5
      - gcc-5
